# Generated by Django 5.1.3 on 2024-11-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
